version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - echo "${CODEBUILD_INITIATOR}"
      - TAG="$(cat source_version)"
      - IMAGE_URI="${ECR_REPOSITORY_URI}:${TAG}"
      - echo "${IMAGE_URI}"
  build:
    commands:
      - docker build --tag "${IMAGE_URI}" .
  post_build:
    commands:
      - docker push "${IMAGE_URI}"
      - printf '[{"name":"%s","imageUri":"%s"}]' "${CONTAINER_NAME}" "${IMAGE_URI}" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json